// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProjectHelloWorld
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProjectHelloWorldPackageString = "287fe538-3e08-4c05-916a-31c9333e2144";
        public static Guid guidVSIXProjectHelloWorldPackage = new Guid(guidVSIXProjectHelloWorldPackageString);

        public const string guidVSIXProjectHelloWorldPackageCmdSetString = "9c904bb4-a653-42e8-861f-073072e727f2";
        public static Guid guidVSIXProjectHelloWorldPackageCmdSet = new Guid(guidVSIXProjectHelloWorldPackageCmdSetString);

        public const string guidImagesString = "0d567dbc-5e60-4648-bbd8-f1f30278705f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}