// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.d33767ca-8089-492d-bdd5-2f7c7509ccc6";
        public const string Name = "VSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
