// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "MyExtension.6c9a5d6e-3509-45c8-900e-ffc91cfb8493";
        public const string Name = "MyExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
