name: Build Extension

on:
  push:
    branches: ["VisualStudio22"]
    tags:
      - 'VisualStudio2022-v*'
  pull_request:
    branches: ["VisualStudio22"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Add NuGet to PATH
        uses: NuGet/setup-nuget@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: "17.0"
          msbuild-architecture: amd64

      - name: Build dependencies
        shell: cmd
        run: |
          cd .scripts
          call build_main.bat

      - name: restore nuget packages
        run: nuget restore visualstudio_2022\geometrydebugger\geometrydebugger.sln

      - name: build geometrydebugger vsix
        run: msbuild visualstudio_2022\geometrydebugger\geometrydebugger\geometrydebugger.csproj /p:configuration=release /p:deployextension=false /p:zippackagecompressionlevel=notcompressed /p:platform=x64
        
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeometryDebugger.vsix
          path: VisualStudio_2022/GeometryDebugger/GeometryDebugger/bin/x64/Release/GeometryDebugger.vsix
      
      - name: Upload GLTool as artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLTool
          path: VisualStudio_2022/GLTool/myinstall_files/
      
      - name: Create ZIP for GLTool
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd VisualStudio_2022/GLTool/myinstall_files/
          zip -r ../../GLTool_myinstall_files.zip ./
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_releaseAdd commentMore actions
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Upload VSIX to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: VisualStudio_2022/GeometryDebugger/GeometryDebugger/bin/x64/Release/GeometryDebugger.vsix
          asset_name: GeometryDebugger.vsix
          asset_content_type: application/vsix
      
      - name: Upload GLTool ZIP to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: VisualStudio_2022/GLTool_myinstall_files.zip
          asset_name: GLTool_myinstall_files.zip
          asset_content_type: application/zip
