name: Build Extension

on:
  push:
    branches: ["VisualStudio22"]
    tags:
    - 'v*'
  pull_request:
    branches: ["VisualStudio22"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
            vs-version: "17.0"
            msbuild-architecture: x64
      - name: Build GeomView
        shell: cmd
        run: |
          cd .scripts
          call install_geomview.bat
        
      - name: Build GLTool
        shell: cmd
        run: |
          cd .scripts
          call install_gltool.bat

      - name: Update version
        run: |
          (Get-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\source.extension.vsixmanifest) |
            ForEach-Object {$_ -Replace '1.0.0', '1.0.${{ github.run_number }}'} |
              Set-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\source.extension.vsixmanifest
          (Get-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\Properties\AssemblyInfo.cs) |
            ForEach-Object {$_ -Replace '1.0.0', '1.0.${{ github.run_number }}'} |
              Set-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\Properties\AssemblyInfo.cs
          (Get-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\Utils\GeometryDebuggerControl.cs) |
            ForEach-Object {$_ -Replace '1.0.0', '1.0.${{ github.run_number }}'} |
              Set-Content -Path VisualStudio_2022\GeometryDebugger\GeometryDebugger\Utils\GeometryDebuggerControl.cs

      - name: Restore
        run: nuget restore VisualStudio_2022\GeometryDebugger\GeometryDebugger.sln

      - name: Build
        run: msbuild VisualStudio_2022\GeometryDebugger\GeometryDebugger\GeometryDebugger.csproj /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=NotCompressed /p:Platform=x64
      
      - uses: actions/upload-artifact@v4
        with:
          name: GeometryDebugger.vsix
          path: VisualStudio_2022\GeometryDebugger\GeometryDebugger\bin\Release\GeometryDebugger.vsix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: MypkaXD/GeometryDebugger
          token: ${{ secrets.GITHUB_TOKEN }}